In [18]:
import os
import pandas as pd

In [19]:
cwd = os.getcwd()
print(cwd)
BASE_DIR = os.path.dirname(cwd)
DATA_DIR =  os.path.join(BASE_DIR, 'PI01_DATA03/DATA')

C:\Users\Usuario\OneDrive\Escritorio\PI01_DATA03

In [20]:
os.listdir(DATA_DIR)

['circuits.csv',
 'constructors.json',
 'drivers.json',
 'races.csv',
 'results.json']

In [21]:
df = pd.DataFrame()

In [22]:
mi_data = os.path.join(DATA_DIR, 'circuits.csv')
print(os.path.exists(mi_data))

True

In [23]:
Circuitos = pd.read_csv(mi_data)

In [24]:
Circuitos.head(n=20)

,circuitId,circuitRef,name,location,country,lat,lng,alt,url
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.968000,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.738000,18,http://en.wikipedia.org/wiki/Sepang_Internatio...
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.510600,7,http://en.wikipedia.org/wiki/Bahrain_Internati...
3,4,catalunya,Circuit de Barcelona-Catalunya,Montmel√≥,Spain,41.57000,2.261110,109,http://en.wikipedia.org/wiki/Circuit_de_Barcel...
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.405000,130,http://en.wikipedia.org/wiki/Istanbul_Park
5,6,monaco,Circuit de Monaco,Monte-Carlo,Monaco,43.73470,7.420560,7,http://en.wikipedia.org/wiki/Circuit_de_Monaco
6,7,villeneuve,Circuit Gilles Villeneuve,Montreal,Canada,45.50000,-73.522800,13,http://en.wikipedia.org/wiki/Circuit_Gilles_Vi...
7,8,magny_cours,Circuit de Nevers Magny-Cours,Magny Cours,France,46.86420,3.163610,228,http://en.wikipedia.org/wiki/Circuit_de_Nevers...
8,9,silverstone,Silverstone Circuit,Silverstone,UK,52.07860,-1.016940,153,http://en.wikipedia.org/wiki/Silverstone_Circuit
9,10,hockenheimring,Hockenheimring,Hockenheim,Germany,49.32780,8.565830,103,http://en.wikipedia.org/wiki/Hockenheimring
10,11,hungaroring,Hungaroring,Budapest,Hungary,47.57890,19.248600,264,http://en.wikipedia.org/wiki/Hungaroring
11,12,valencia,Valencia Street Circuit,Valencia,Spain,39.45890,-0.331667,4,http://en.wikipedia.org/wiki/Valencia_Street_C...
12,13,spa,Circuit de Spa-Francorchamps,Spa,Belgium,50.43720,5.971390,401,http://en.wikipedia.org/wiki/Circuit_de_Spa-Fr...
13,14,monza,Autodromo Nazionale di Monza,Monza,Italy,45.61560,9.281110,162,http://en.wikipedia.org/wiki/Autodromo_Naziona...
14,15,marina_bay,Marina Bay Street Circuit,Marina Bay,Singapore,1.29140,103.864000,18,http://en.wikipedia.org/wiki/Marina_Bay_Street...
15,16,fuji,Fuji Speedway,Oyama,Japan,35.37170,138.927000,583,http://en.wikipedia.org/wiki/Fuji_Speedway
16,17,shanghai,Shanghai International Circuit,Shanghai,China,31.33890,121.220000,5,http://en.wikipedia.org/wiki/Shanghai_Internat...
17,18,interlagos,Aut√≥dromo Jos√© Carlos Pace,S√£o Paulo,Brazil,-23.70360,-46.699700,785,http://en.wikipedia.org/wiki/Aut%C3%B3dromo_Jo...
18,19,indianapolis,Indianapolis Motor Speedway,Indianapolis,USA,39.79500,-86.234700,223,http://en.wikipedia.org/wiki/Indianapolis_Moto...
19,20,nurburgring,N√ºrburgring,N√ºrburg,Germany,50.33560,6.947500,578,http://en.wikipedia.org/wiki/N%C3%BCrburgring

In [26]:
mi_data2 = os.path.join(DATA_DIR, 'races.csv')
print(os.path.exists(mi_data))

True

In [27]:
Carreras = pd.read_csv(mi_data2)
Carreras.head(n=20)

,raceId,year,round,circuitId,name,date,time,url
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...
5,6,2009,6,6,Monaco Grand Prix,2009-05-24,12:00:00,http://en.wikipedia.org/wiki/2009_Monaco_Grand...
6,7,2009,7,5,Turkish Grand Prix,2009-06-07,12:00:00,http://en.wikipedia.org/wiki/2009_Turkish_Gran...
7,8,2009,8,9,British Grand Prix,2009-06-21,12:00:00,http://en.wikipedia.org/wiki/2009_British_Gran...
8,9,2009,9,20,German Grand Prix,2009-07-12,12:00:00,http://en.wikipedia.org/wiki/2009_German_Grand...
9,10,2009,10,11,Hungarian Grand Prix,2009-07-26,12:00:00,http://en.wikipedia.org/wiki/2009_Hungarian_Gr...
10,11,2009,11,12,European Grand Prix,2009-08-23,12:00:00,http://en.wikipedia.org/wiki/2009_European_Gra...
11,12,2009,12,13,Belgian Grand Prix,2009-08-30,12:00:00,http://en.wikipedia.org/wiki/2009_Belgian_Gran...
12,13,2009,13,14,Italian Grand Prix,2009-09-13,12:00:00,http://en.wikipedia.org/wiki/2009_Italian_Gran...
13,14,2009,14,15,Singapore Grand Prix,2009-09-27,12:00:00,http://en.wikipedia.org/wiki/2009_Singapore_Gr...
14,15,2009,15,22,Japanese Grand Prix,2009-10-04,05:00:00,http://en.wikipedia.org/wiki/2009_Japanese_Gra...
15,16,2009,16,18,Brazilian Grand Prix,2009-10-18,16:00:00,http://en.wikipedia.org/wiki/2009_Brazilian_Gr...
16,17,2009,17,24,Abu Dhabi Grand Prix,2009-11-01,11:00:00,http://en.wikipedia.org/wiki/2009_Abu_Dhabi_Gr...
17,18,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...
18,19,2008,2,2,Malaysian Grand Prix,2008-03-23,07:00:00,http://en.wikipedia.org/wiki/2008_Malaysian_Gr...
19,20,2008,3,3,Bahrain Grand Prix,2008-04-06,11:30:00,http://en.wikipedia.org/wiki/2008_Bahrain_Gran...

In [28]:
mi_data3 = os.path.join(DATA_DIR, 'drivers.json')
print(os.path.exists(mi_data3))

True

In [59]:
Pilotos = pd.read_json(mi_data3,lines=True)
Pilotos.head(n=10)

,driverId,driverRef,number,code,name,dob,nationality,url
0,1,hamilton,44,HAM,"{'forename': 'Lewis', 'surname': 'Hamilton'}",1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,"{'forename': 'Nick', 'surname': 'Heidfeld'}",1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,"{'forename': 'Nico', 'surname': 'Rosberg'}",1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,"{'forename': 'Fernando', 'surname': 'Alonso'}",1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,"{'forename': 'Heikki', 'surname': 'Kovalainen'}",1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
5,6,nakajima,\N,NAK,"{'forename': 'Kazuki', 'surname': 'Nakajima'}",1985-01-11,Japanese,http://en.wikipedia.org/wiki/Kazuki_Nakajima
6,7,bourdais,\N,BOU,"{'forename': 'S√©bastien', 'surname': 'Bourdais'}",1979-02-28,French,http://en.wikipedia.org/wiki/S%C3%A9bastien_Bo...
7,8,raikkonen,7,RAI,"{'forename': 'Kimi', 'surname': 'R√§ikk√∂nen'}",1979-10-17,Finnish,http://en.wikipedia.org/wiki/Kimi_R%C3%A4ikk%C...
8,9,kubica,88,KUB,"{'forename': 'Robert', 'surname': 'Kubica'}",1984-12-07,Polish,http://en.wikipedia.org/wiki/Robert_Kubica
9,10,glock,\N,GLO,"{'forename': 'Timo', 'surname': 'Glock'}",1982-03-18,German,http://en.wikipedia.org/wiki/Timo_Glock

In [30]:
mi_data4 = os.path.join(DATA_DIR, 'constructors.json') 
print(os.path.exists(mi_data4))

True

In [31]:
Contructores= pd.read_json(mi_data4,lines=True)
Contructores.head(n=25)

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso
5,6,ferrari,Ferrari,Italian,http://en.wikipedia.org/wiki/Scuderia_Ferrari
6,7,toyota,Toyota,Japanese,http://en.wikipedia.org/wiki/Toyota_Racing
7,8,super_aguri,Super Aguri,Japanese,http://en.wikipedia.org/wiki/Super_Aguri_F1
8,9,red_bull,Red Bull,Austrian,http://en.wikipedia.org/wiki/Red_Bull_Racing
9,10,force_india,Force India,Indian,http://en.wikipedia.org/wiki/Racing_Point_Forc...
10,11,honda,Honda,Japanese,http://en.wikipedia.org/wiki/Honda_Racing_F1
11,12,spyker,Spyker,Dutch,http://en.wikipedia.org/wiki/Spyker_F1
12,13,mf1,MF1,Russian,http://en.wikipedia.org/wiki/Midland_F1_Racing
13,14,spyker_mf1,Spyker MF1,Dutch,http://en.wikipedia.org/wiki/Midland_F1_Racing
14,15,sauber,Sauber,Swiss,http://en.wikipedia.org/wiki/Sauber
15,16,bar,BAR,British,http://en.wikipedia.org/wiki/British_American_...
16,17,jordan,Jordan,Irish,http://en.wikipedia.org/wiki/Jordan_Grand_Prix
17,18,minardi,Minardi,Italian,http://en.wikipedia.org/wiki/Minardi
18,19,jaguar,Jaguar,British,http://en.wikipedia.org/wiki/Jaguar_Racing
19,20,prost,Prost,French,http://en.wikipedia.org/wiki/Prost_Grand_Prix
20,21,arrows,Arrows,British,http://en.wikipedia.org/wiki/Arrows_Grand_Prix...
21,22,benetton,Benetton,Italian,http://en.wikipedia.org/wiki/Benetton_Formula
22,23,brawn,Brawn,British,http://en.wikipedia.org/wiki/Brawn_GP
23,24,stewart,Stewart,British,http://en.wikipedia.org/wiki/Stewart_Grand_Prix
24,25,tyrrell,Tyrrell,British,http://en.wikipedia.org/wiki/Tyrrell_Racing

In [32]:
mi_data5 = os.path.join(DATA_DIR, 'results.json') 
print(os.path.exists(mi_data5))

True

In [60]:
Resultados = pd.read_json(mi_data5,lines=True)
Resultados.tail(n=40)

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
24920,24926,1046,815,211,11,5,1,1,1,25.0,87,1:31:15.114,5475114,69,3,0:56.789,224.599,1
24921,24927,1046,839,4,31,11,2,2,2,18.0,87,+10.518,5485632,75,12,0:57.350,222.402,1
24922,24928,1046,840,211,18,10,3,3,3,15.0,87,+11.869,5486983,85,14,0:57.388,222.255,1
24923,24929,1046,832,1,55,8,4,4,4,12.0,87,+12.580,5487694,80,9,0:57.165,223.122,1
24924,24930,1046,817,4,3,7,5,5,5,10.0,87,+13.330,5488444,57,6,0:56.979,223.85,1
24925,24931,1046,848,9,23,12,6,6,6,8.0,87,+13.842,5488956,52,8,0:57.056,223.548,1
24926,24932,1046,826,213,26,6,7,7,7,6.0,87,+14.534,5489648,80,7,0:57.001,223.764,1
24927,24933,1046,822,131,77,1,8,8,8,4.0,87,+15.389,5490503,60,2,0:56.563,225.497,1
24928,24934,1046,847,131,63,2,9,9,9,3.0,87,+18.556,5493670,80,1,0:55.404,230.214,1
24929,24935,1046,846,1,4,19,10,10,10,1.0,87,+19.541,5494655,85,11,0:57.270,222.713,1
24930,24936,1046,842,213,10,9,11,11,11,0.0,87,+20.527,5495641,53,10,0:57.220,222.908,1
24931,24937,1046,20,6,5,13,12,12,12,0.0,87,+22.611,5497725,56,5,0:56.905,224.141,1
24932,24938,1046,841,51,99,14,13,13,13,0.0,87,+24.111,5499225,56,4,0:56.887,224.212,1
24933,24939,1046,8,51,7,18,14,14,14,0.0,87,+26.153,5501267,56,13,0:57.375,222.305,1
24934,24940,1046,825,210,20,15,15,15,15,0.0,87,+32.370,5507484,57,16,0:57.516,221.76,1
24935,24941,1046,851,3,89,17,16,16,16,0.0,87,+33.674,5508788,56,15,0:57.392,222.24,1
24936,24942,1046,850,210,51,20,17,17,17,0.0,87,+36.858,5511972,56,17,0:57.742,220.892,1
24937,24943,1046,849,3,6,16,\N,R,18,0.0,52,\N,\N,29,18,0:58.206,219.132,5
24938,24944,1046,830,9,33,3,\N,R,19,0.0,0,\N,\N,\N,0,\N,\N,3
24939,24945,1046,844,6,16,4,\N,R,20,0.0,0,\N,\N,\N,0,\N,\N,4
24940,24946,1047,830,9,33,1,1,1,1,25.0,55,1:36:28.645,5788645,14,2,1:40.958,198.046,1
24941,24947,1047,822,131,77,2,2,2,2,18.0,55,+15.976,5804621,40,3,1:41.131,197.707,1
24942,24948,1047,1,131,44,3,3,3,3,15.0,55,+18.415,5807060,37,5,1:41.420,197.144,1
24943,24949,1047,848,9,23,5,4,4,4,12.0,55,+19.987,5808632,42,4,1:41.227,197.52,1
24944,24950,1047,846,1,4,4,5,5,5,10.0,55,+1:00.729,5849374,53,12,1:41.964,196.092,1
24945,24951,1047,832,1,55,6,6,6,6,8.0,55,+1:05.662,5854307,48,11,1:41.947,196.125,1
24946,24952,1047,817,4,3,11,7,7,7,7.0,55,+1:13.748,5862393,55,1,1:40.926,198.109,1
24947,24953,1047,842,213,10,9,8,8,8,4.0,55,+1:29.718,5878363,53,15,1:42.474,195.116,1
24948,24954,1047,839,4,31,10,9,9,9,2.0,55,+1:41.069,5799996,47,18,1:42.894,194.32,1
24949,24955,1047,840,211,18,8,10,10,10,1.0,55,+1:42.738,5790314,41,9,1:41.866,196.281,1
24950,24956,1047,826,213,26,7,11,11,11,0.0,54,\N,\N,47,17,1:42.704,194.679,11
24951,24957,1047,8,51,7,15,12,12,12,0.0,54,\N,\N,53,14,1:42.148,195.739,11
24952,24958,1047,844,6,16,12,13,13,13,0.0,54,\N,\N,24,10,1:41.908,196.2,11
24953,24959,1047,20,6,5,13,14,14,14,0.0,54,\N,\N,37,6,1:41.475,197.037,11
24954,24960,1047,847,3,63,16,15,15,15,0.0,54,\N,\N,54,20,1:43.328,193.504,11
24955,24961,1047,841,51,99,14,16,16,16,0.0,54,\N,\N,29,7,1:41.675,196.65,11
24956,24962,1047,849,3,6,18,17,17,17,0.0,54,\N,\N,49,16,1:42.497,195.073,11
24957,24963,1047,825,210,20,20,18,18,18,0.0,54,\N,\N,50,13,1:41.999,196.025,11
24958,24964,1047,850,210,51,17,19,19,19,0.0,53,\N,\N,50,8,1:41.707,196.588,12
24959,24965,1047,815,211,11,19,\N,R,20,0.0,8,\N,\N,6,19,1:43.263,193.625,7

In [39]:
Anio_con_mas_carreras = Carreras['year'].value_counts().idxmax()
Anio_con_mas_carreras

2021

In [40]:
circuito_mas = pd.merge(Carreras, Circuitos, on='circuitId')
circuito_mas

,raceId,year,round,circuitId,name_x,date,time,url_x,circuitRef,name_y,location,country,lat,lng,alt,url_y
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.9680,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
1,18,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.9680,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
2,36,2007,1,1,Australian Grand Prix,2007-03-18,03:00:00,http://en.wikipedia.org/wiki/2007_Australian_G...,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.9680,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
3,55,2006,3,1,Australian Grand Prix,2006-04-02,14:00:00,http://en.wikipedia.org/wiki/2006_Australian_G...,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.9680,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
4,71,2005,1,1,Australian Grand Prix,2005-03-06,14:00:00,http://en.wikipedia.org/wiki/2005_Australian_G...,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.9680,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1053,1013,2019,4,73,Azerbaijan Grand Prix,2019-04-28,12:10:00,https://en.wikipedia.org/wiki/2019_Azerbaijan_...,BAK,Baku City Circuit,Baku,Azerbaijan,40.3725,49.8533,-7,http://en.wikipedia.org/wiki/Baku_City_Circuit
1054,1057,2021,6,73,Azerbaijan Grand Prix,2021-06-06,12:00:00,http://en.wikipedia.org/wiki/2021_Azerbaijan_G...,BAK,Baku City Circuit,Baku,Azerbaijan,40.3725,49.8533,-7,http://en.wikipedia.org/wiki/Baku_City_Circuit
1055,1039,2020,9,76,Tuscan Grand Prix,2020-09-13,13:10:00,https://en.wikipedia.org/wiki/2020_Tuscan_Gran...,mugello,Autodromo Internazionale del Mugello,Mugello,Italy,43.9975,11.3719,255,http://en.wikipedia.org/wiki/Mugello_Circuit
1056,1042,2020,12,75,Portuguese Grand Prix,2020-10-25,12:10:00,https://en.wikipedia.org/wiki/2020_Portuguese_...,portimao,Aut√≥dromo Internacional do Algarve,Portim√£o,Portugal,37.2270,-8.6267,108,http://en.wikipedia.org/wiki/Algarve_Internati...
1057,1072,2021,22,77,Saudi Arabian Grand Prix,2021-12-05,16:00:00,http://en.wikipedia.org/wiki/2021_Saudi_Arabia...,jeddah,Jeddah Street Circuit,Jeddah,Saudi Arabia,21.5433,39.1728,15,http://en.wikipedia.org/wiki/Jeddah_Street_Cir...

In [51]:
Circuito_data_clean = circuito_mas.drop(columns=['name_x','date','url_x','lat','lng','alt','time','url_y',])
Circuito_data_clean

,raceId,year,round,circuitId,circuitRef,name_y,location,country
0,1,2009,1,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia
1,18,2008,1,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia
2,36,2007,1,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia
3,55,2006,3,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia
4,71,2005,1,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia
...,...,...,...,...,...,...,...,...
1053,1013,2019,4,73,BAK,Baku City Circuit,Baku,Azerbaijan
1054,1057,2021,6,73,BAK,Baku City Circuit,Baku,Azerbaijan
1055,1039,2020,9,76,mugello,Autodromo Internazionale del Mugello,Mugello,Italy
1056,1042,2020,12,75,portimao,Aut√≥dromo Internacional do Algarve,Portim√£o,Portugal
1057,1072,2021,22,77,jeddah,Jeddah Street Circuit,Jeddah,Saudi Arabia

In [55]:
Circuito_mas_corrido = Circuito_data_clean['name_y'].value_counts()
Circuito_mas_corrido

Autodromo Nazionale di Monza       71
Circuit de Monaco                  67
Silverstone Circuit                56
Circuit de Spa-Francorchamps       54
N√ºrburgring                        42
                                   ..
AVUS                                1
Riverside International Raceway     1
Zeltweg                             1
Le Mans                             1
Jeddah Street Circuit               1
Name: name_y, Length: 75, dtype: int64

In [62]:
Piloto_mas_ganador = pd.merge(Pilotos, Resultados, on='driverId')
Piloto_mas_ganador

,driverId,driverRef,number_x,code,name,dob,nationality,url,resultId,raceId,...,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,hamilton,44,HAM,"{'forename': 'Lewis', 'surname': 'Hamilton'}",1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton,1,18,...,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.3,1
1,1,hamilton,44,HAM,"{'forename': 'Lewis', 'surname': 'Hamilton'}",1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton,27,19,...,5,4.0,56,+46.548,5525103,53,3,1:35.462,209.033,1
2,1,hamilton,44,HAM,"{'forename': 'Lewis', 'surname': 'Hamilton'}",1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton,57,20,...,13,0.0,56,\N,\N,25,19,1:35.520,203.969,11
3,1,hamilton,44,HAM,"{'forename': 'Lewis', 'surname': 'Hamilton'}",1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton,69,21,...,3,6.0,66,+4.187,5903238,20,3,1:22.017,204.323,1
4,1,hamilton,44,HAM,"{'forename': 'Lewis', 'surname': 'Hamilton'}",1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton,90,22,...,2,8.0,58,+3.779,5213230,31,2,1:26.529,222.085,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24955,849,latifi,6,LAT,"{'forename': 'Nicholas', 'surname': 'Latifi'}",1995-06-29,Canadian,http://en.wikipedia.org/wiki/Nicholas_Latifi,24943,1046,...,18,0.0,52,\N,\N,29,18,0:58.206,219.132,5
24956,849,latifi,6,LAT,"{'forename': 'Nicholas', 'surname': 'Latifi'}",1995-06-29,Canadian,http://en.wikipedia.org/wiki/Nicholas_Latifi,24962,1047,...,17,0.0,54,\N,\N,49,16,1:42.497,195.073,11
24957,850,pietro_fittipaldi,51,FIT,"{'forename': 'Pietro', 'surname': 'Fittipaldi'}",1996-06-25,Brazilian,http://en.wikipedia.org/wiki/Pietro_Fittipaldi,24942,1046,...,17,0.0,87,+36.858,5511972,56,17,0:57.742,220.892,1
24958,850,pietro_fittipaldi,51,FIT,"{'forename': 'Pietro', 'surname': 'Fittipaldi'}",1996-06-25,Brazilian,http://en.wikipedia.org/wiki/Pietro_Fittipaldi,24964,1047,...,19,0.0,53,\N,\N,50,8,1:41.707,196.588,12
24959,851,aitken,89,AIT,"{'forename': 'Jack', 'surname': 'Aitken'}",1995-09-23,British,http://en.wikipedia.org/wiki/Jack_Aitken,24941,1046,...,16,0.0,87,+33.674,5508788,56,15,0:57.392,222.24,1

In [64]:
piloto_mas_ganador = Piloto_mas_ganador.drop(columns=['url','dob','code','laps','time','milliseconds','fastestLap','fastestLapTime','fastestLapSpeed'])

In [66]:
piloto_mas_ganador

,driverId,driverRef,number_x,name,nationality,resultId,raceId,constructorId,number_y,grid,position,positionText,positionOrder,points,rank,statusId
0,1,hamilton,44,"{'forename': 'Lewis', 'surname': 'Hamilton'}",British,1,18,1,22,1,1,1,1,10.0,2,1
1,1,hamilton,44,"{'forename': 'Lewis', 'surname': 'Hamilton'}",British,27,19,1,22,9,5,5,5,4.0,3,1
2,1,hamilton,44,"{'forename': 'Lewis', 'surname': 'Hamilton'}",British,57,20,1,22,3,13,13,13,0.0,19,11
3,1,hamilton,44,"{'forename': 'Lewis', 'surname': 'Hamilton'}",British,69,21,1,22,5,3,3,3,6.0,3,1
4,1,hamilton,44,"{'forename': 'Lewis', 'surname': 'Hamilton'}",British,90,22,1,22,3,2,2,2,8.0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24955,849,latifi,6,"{'forename': 'Nicholas', 'surname': 'Latifi'}",Canadian,24943,1046,3,6,16,\N,R,18,0.0,18,5
24956,849,latifi,6,"{'forename': 'Nicholas', 'surname': 'Latifi'}",Canadian,24962,1047,3,6,18,17,17,17,0.0,16,11
24957,850,pietro_fittipaldi,51,"{'forename': 'Pietro', 'surname': 'Fittipaldi'}",Brazilian,24942,1046,210,51,20,17,17,17,0.0,17,1
24958,850,pietro_fittipaldi,51,"{'forename': 'Pietro', 'surname': 'Fittipaldi'}",Brazilian,24964,1047,210,51,17,19,19,19,0.0,8,12
24959,851,aitken,89,"{'forename': 'Jack', 'surname': 'Aitken'}",British,24941,1046,3,89,17,16,16,16,0.0,15,1

In [67]:
Pilotos_mas_ganadores = piloto_mas_ganador.drop(columns=['number_y','name','rank','statusId'])
Pilotos_mas_ganadores

,driverId,driverRef,number_x,nationality,resultId,raceId,constructorId,grid,position,positionText,positionOrder,points
0,1,hamilton,44,British,1,18,1,1,1,1,1,10.0
1,1,hamilton,44,British,27,19,1,9,5,5,5,4.0
2,1,hamilton,44,British,57,20,1,3,13,13,13,0.0
3,1,hamilton,44,British,69,21,1,5,3,3,3,6.0
4,1,hamilton,44,British,90,22,1,3,2,2,2,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...
24955,849,latifi,6,Canadian,24943,1046,3,16,\N,R,18,0.0
24956,849,latifi,6,Canadian,24962,1047,3,18,17,17,17,0.0
24957,850,pietro_fittipaldi,51,Brazilian,24942,1046,210,20,17,17,17,0.0
24958,850,pietro_fittipaldi,51,Brazilian,24964,1047,210,17,19,19,19,0.0
24959,851,aitken,89,British,24941,1046,3,17,16,16,16,0.0

In [75]:
Circuito_mas_corrido.to_csv(Circuito)

NameError: name 'Circuito' is not defined